In [1]:
import numpy as np

In [16]:
s = np.array(5)
print(s.ndim)
print(s.shape)
print("==========")
v = np.array([1,2,3])
print(v.ndim)
print("==========")
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
             ])

print(m.ndim)
print("==========")
print(m.shape)

0
()
1
2
(3, 3)


In [19]:
vec_1 = np.array([1,2,3,4,5,6])
mat_1 = vec_1.reshape((3,2))
# vec_1.shape
print(vec_1)
print(mat_1)



[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [25]:
vec_2 = np.array([1,2,3,4])
mat_2 = vec_2.reshape(vec_2.shape[0],1)
mat_2

array([[1],
       [2],
       [3],
       [4]])

In [23]:
vec_2.shape[0]

4

In [28]:
vec_2[:,None]

array([[1],
       [2],
       [3],
       [4]])

In [37]:
mat = np.array([[False,True,3.1],
                [4,5,6],
                [7,8,9]
])

mat.dtype
# mat

dtype('float64')

In [38]:
class c:
    x = 3
o1 = c()  

In [41]:
mat = np.array([[False,True,"mona"],
                [4,5,6],
                [7,8,9]
])

print(mat)
print(mat.dtype)

[['False' 'True' 'mona']
 ['4' '5' '6']
 ['7' '8' '9']]
<U21


In [42]:
mat = np.array([[False,True,"mona"],
                [4,5,6],
                [7,8,9],
                [0,0,0]
])

mat[1,-2]

np.str_('5')

In [50]:
mat= np.array([[1,2,3,4,5,6],
              [7,2,9,4,5,6],
              [1,5,3,4,5,6]
              ])
mat[-3:-1 , -3:-1]

array([[4, 5],
       [4, 5]])

In [51]:
transpose = mat.T
transpose

array([[1, 7, 1],
       [2, 2, 5],
       [3, 9, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [52]:
mat = np.zeros((3,4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
mat = np.ones((3,4))
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
mat = np.identity(3,dtype= 'float32')
mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [2]:
mat = np.full((3,3),5)

mat

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [3]:
a = ['ali',10,True,'amir']
np.random.choice(a , size = (3,5))

array([['10', 'ali', '10', '10', 'True'],
       ['True', 'ali', '10', '10', 'ali'],
       ['10', '10', 'ali', 'amir', 'amir']], dtype='<U21')

In [1]:
import numpy as np

In [2]:
mat_1 = np.ones((3,4))
mat_2 = np.zeros((5,3))